# docker-compose.yml fuer Citrix-ICA-Client-Container
# Deutsche Bahn DB Systel, Projekt DSR
#
# Heiko G.,      2017-07-07

version: "2"
services:
  icaclient:
    build:          .
    image:          7lima/icaclient
#   container_name: icaclient
#   network_mode:   host
#   privileged:     true
    environment:
    - WEB_URL                                   # weiterreichen
